version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest

commands:
  yarn-install:
    steps:
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "package.json" }}
      - run:
          name: install yarn
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    steps:
      - run:
          name: eslint
          command: yarn run lint
      - run:
          name: stylelint
          command: yarn run lint:css
  test:
    steps:
      - run:
          name: test
          command: yarn run test
  build:
    steps:
      - run:
          name: yarn run build
          command: yarn run build
  deploy:
    steps:
      - run:
          name: deploy staging
          command: ./node_modules/.bin/gulp deploy

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - yarn-install
      - lint
      - test
  deploy-stg:
    executor:
      name: default
    steps:
      - checkout
      - yarn-install
      - lint
      - test
      - build
      - deploy
      - slack/status:
          success_message: ':circleci-pass: $CIRCLE_BRANCH のstagingへのデプロイが完了しました\n:github_octocat: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-fail: $CIRCLE_BRANCH のstagingへのデプロイが失敗しました\n:github_octocat: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'
    environment:
      AWS_BUCKET_NAME: next-circleci-sample-staging.s3.amazonaws.com
      AWS_CLOUDFRONT: EIW61NBHTXSAX
  deploy-prod:
    executor:
      name: default
    steps:
      - checkout
      - yarn-install
      - lint
      - test
      - build
      - deploy
      - slack/status:
          success_message: ':circleci-pass: $CIRCLE_BRANCH のproductionへのデプロイが完了しました\n:github_octocat: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-fail: $CIRCLE_BRANCH のproductionへのデプロイが失敗しました\n:github_octocat: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'
    environment:
      AWS_BUCKET_NAME: arn:aws:s3:::next-circleci-sample-production
      AWS_CLOUDFRONT: E2OPITUFPPKBNM

workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy-stg:
          requires:
            - test
          filters:
            branches:
              only: staging
      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only: main
